local mapa = {
  ambient="0.1,0.1,0.1",
  gravity="0 -9.8 0",
  entities={
    {
      name="Camera",
      id=2,
      components={
        transform={
          position="0,0,200",
          rotation="0,0,0",
          scale="1,1,1",
          parent="-1"
        },
        camera={
          near="0.1",
          far="1000",
          autoaspect="true",
          aspect="1.78",
          fov="50",
          proyection="1",
          viewport="0,0,1,1",
          color="1.0,0.5,0.3137"
        }
        ,
        skybox={
          enable="true",
          planenormal="Z",
          planepos="20",
          materialname="sky/space",
          scale="1",
          tiling="1",
          drawfirst="true",
          bow="10.0",
          xsegments="10",
          ysegments="10"
        }
      }
    },
    {
    	name="Imagen",
    	id=5,
    	components={
        transform={
          position="0,0,0",
          rotation="0,0,0",
          scale="1,1,1",
          parent="-1"
        },
        text={
          text="lamo",
          position="0.5,0.5",
          size="100,100",
          name="textoPrueba",
          properties="BackgroundEnabled,false,FrameEnabled,false,TextColours,tl:FF000000 tr:FF000000 bl:FF000000 br:FF000000"
        },
        image={
          source="TaharezLook/MouseArrow",
          position="0.2,0.2",
          size="100,100",
          name="imagenPrueba",
          properties="BackgroundEnabled,false,FrameEnabled,false,Image,TaharezLook/MouseArrow"
        },
        button={
          text="Salir",
          position="0.35,0.4",
          size="200,100",
          name="botonJugar",
          type="EXIT",
          showCursor="true",
          continueBullet="true",
          nextScene="level.lua"
          --properties="Normal,TaharezLook/ButtonLeftNormal"
        }
    	}
    }
  }
}

function GetMapa ()
  return mapa
end